#version: '3'

services:
    nginx:
       image: nginx:latest
       ports:
           - '8810:80'
       volumes:
           - ./:/var/www/
           - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
       container_name: server_app

    app:
        build:
            context: .
            dockerfile: Docker/php/DockerFile
        volumes:
            - ./:/var/www
        container_name: laravel_app

    db:
        image: mysql:8.0
        restart: no
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./Docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        environment:
            MYSQL_DATABASE: laramysqldocker
            MYSQL_ROOT_PASSWORD: 3003
        ports:
                - '8763:3306'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: proj_db #название сервиса

